
name="whole-faca-1-masknce=0.1-pos=cos-style500-att"
#sotaname="refine-G-4-effect-masknce=0.1-pos=cos-style500"

CUDA_VISIBLE_DEVICES="4,7,6,5" python -m torch.distributed.launch --nproc_per_node 4 --master_port 7992 train_whole.py  --name $name --lr 0.0002 --netG spadeunetw --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1,2,3  --no_instance --no_skip_connections --batchSize 8 --mix_input_gen --nThreads 8 --bbox --segmentation_mask --netD divcomultiscale --serial_batches --model whole --niter 80 --niter_decay 120 --netE vae --effect --use_style_loss --lambda_masknce 0.1 --lambda_style 500 --netF patch --eord --fakeattention --no_inpaint


CUDA_VISIBLE_DEVICES="4,7,6,5" python -m torch.distributed.launch --nproc_per_node 4 --master_port 7992 train_whole.py  --name $name --lr 0.0001 --netG spadeunetw --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1,2,3  --no_instance --no_skip_connections --batchSize 8 --mix_input_gen --nThreads 8 --bbox --segmentation_mask --netD divcomultiscale --serial_batches --model whole --niter 80 --niter_decay 200 --netE vae --effect  --masknce --negtype frompos --use_style_loss --lambda_masknce 0.1 --lambda_style 500 --continue_train --use_queue --netF maskboxque --rand_pos_que --eord --fakeattention --no_inpaint
#CUDA_VISIBLE_DEVICES="0,1,2,3" python -m torch.distributed.launch --nproc_per_node 4 --master_port 9999 train_whole.py  --name $name --lr 0.0001 --netG spadeunetw --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1,2,3  --no_instance --no_skip_connections --batchSize 8 --mix_input_gen --nThreads 4 --bbox --segmentation_mask --netD divcomultiscale --serial_batches --model refineg --niter 0 --niter_decay 40 --netE vae  --masknce --netF maskbox --effect --negtype frombg


CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --removal --which_epoch 130 
CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --addition --which_epoch 130
CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --removal --which_epoch 130 
CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --addition --which_epoch 130 
CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --removal  
CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --addition 
CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --removal 
CUDA_VISIBLE_DEVICES="6,7,5" python -m torch.distributed.launch --nproc_per_node 2  --master_port 9901 test_whole.py  --no_inpaint  --results_dir ./results_whole/  --name $name --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0,1 --netG spadeunetw --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netE vae --eord --addition  

python cal_ind_whole.py
python cal_ind_whole.py

#CUDA_VISIBLE_DEVICES="4" python -m torch.distributed.launch --nproc_per_node 1 --master_port 9999 train.py  --name only-E-1 --lr 0.0002 --netG spadeunetw --dataset_mode Efacabox --dataroot ../../datasets/facade/ --gpu 0  --no_instance --no_skip_connections --batchSize 2 --mix_input_gen --nThreads 0 --bbox --segmentation_mask --netD divcomultiscale --eord --serial_batches --model learneord --effect --no_vgg_loss --cost_type hard `
